config/routes.rb
SunnyTutorial::Application.routes.draw do
  resources :users
  resources :student_infos
  resources :tutor_infos
  resources :searches
  resources :messages
  get 'login' => "sessions#new", as: :log_in
  match 'logout' => "sessions#destroy", as: :log_out
  get 'signup' => "users#create", as: :sign_up
  resources :sessions, only: :create
  root to: 'static_page#home', as: :home
  get 'guangzhou' => 'static_page#display', as: :guangzhou
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
   layout 'application', except: :home
   def display
     @tutor_infos = TutorInfo.order("created_at DESC").limit(10)
     @student_infos = StudentInfo.order("created_at DESC").limit(10)
   end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/display.html.erb
<ul id="left" class="thumbnails">
  <li class="span5">
  <div class="thumbnail">
  <h4>最新教员</h4>
  <ul>
    <% @tutor_infos.each do |t| %>
      <li>
        <a href="<%= tutor_info_path(t) %>">
        <div class="c_a"><%= t.username %></div>
        <div class="c_c"><%= t.school%></div>
        <div class="c_c"><%= t.major%></div>
        <div class="c_a"><%= t.created_at.strftime("%m-%d")%></div>
        </a>
      </li>
    <% end %>
  </ul>
  <div class="text-right"><%= link_to "更多", tutor_infos_path %></div>
  </div>
  </li>
</ul>
<ul id="right" class="thumbnails">
  <li class="span5">
  <div class="thumbnail">
  <h4>最新学员</h4>
  <ul>
    <% @student_infos.each do |s| %>
      <li>
        <a href="<%= student_info_path(s) %>">
          <div class="c_a"><%= s.grade%></div>
          <div class="c_a"><%= s.area %></div>
          <div class="c_a"><%= s.subject_list%></div>
          <div class="c_b"><%= truncate(strip_tags(s.demand), length:15) %></div>
          <div class="c_a"><%= s.created_at.strftime("%m-%d")%></div>
        </a>
      </li>
    <% end %>
  </ul>
  <div class="text-right"><%= link_to "更多", student_infos_path %></div>
  </div>
  </li>
</ul>
<hr />

app/views/static_page/home.html.erb
<%= image_tag 'title.jpg', class: "img-rounded", id: "title_img" %>
<div id="title">
<p class="text-left">Sunny</p> 
<p class="text-center">家教网</p>
</div>
<div class="homes">
<div class="navbar">
   <div class="navbar-inner">
     <ul class="nav">
        <li class="divider-vertical"><%= link_to "广州站", guangzhou_path %></li>
        <li class="divider-vertical"><%= link_to "教员库", student_infos_path%></li>
        <li class="divider-vertical"><%= link_to "学员库", tutor_infos_path %></li>
        <li class="divider-vertical"><%= link_to "请家教", new_student_info_path %></li>
        <li class="divider-vertical"><%= link_to "做家教", new_tutor_info_path %></li>
        <li class="divider-vertical"><%= link_to "讨论区", messages_path %></li>
     </ul>
     <ul class="nav pull-right">
        <li><a href="javascript:void(0)" onClick="addCookie()" >收藏本站</a></li>
     </ul>
   </div>
</div>
</div>