config/routes.rb
SunnyTutorial::Application.routes.draw do
  resources :users
  resources :student_infos
  resources :tutor_infos
  resources :searches
  resources :messages
  get 'login' => "sessions#new", as: :log_in
  match 'logout' => "sessions#destroy", as: :log_out
  get 'signup' => "users#create", as: :sign_up
  resources :sessions, only: :create
  root to: 'static_page#home', as: :home
  get 'guangzhou' => 'static_page#display', as: :guangzhou
end

app/models/student_info.rb
class StudentInfo < ActiveRecord::Base
  attr_accessible :address, :area, :demand, :fee, :gender, :grade, :phone, :status, :time, :username, :user_id, :subject_list
  validates_presence_of :address, :area, :demand, :fee, :gender, :grade, :phone, :time, :username, :subject_list
  has_many :teachings
  has_many :subjects, through: :teachings
  belongs_to :user
  default_scope order("created_at DESC")

  def subject_list=(names)
    self.subjects = names.split(",").map do |n|
      Subject.find_by_name(n)
    end
  end

  def subject_list
    subjects.map(&:name).join(',')
  end
end

app/controllers/student_infos_controller.rb
class StudentInfosController < ApplicationController
  load_and_authorize_resource

  def index
    @student_infos = params[:search_id] ? Search.find(params[:search_id]).find_student_infos : StudentInfo.all
    @search = Search.new(search_type: "student")
  end
  
  def new
    @student_info = StudentInfo.new
  end

  def create
    @student_info = StudentInfo.new(params[:student_info].merge!(user_id: current_user.id))
    if @student_info.save
      redirect_to @student_info, notice: "创建成功"
    else
      render :new
    end
  end

  def update
    if @student_info.update_attributes(params[:student_info])
      redirect_to @student_info, notice: "修改成功"
    else
      render :edit
    end
  end
end

app/views/student_infos/_form.html.erb
<%= simple_form_for @student_info, html: {class: 'form-horizontal'} do |f| %>
  <legend>家教信息填写</legend>
  <%= f.input :username  %>
  <%= f.input :gender, collection: ["男","女"], as: :radio_buttons %>
  <%= f.input :phone %>
  <%= f.input :area, collection: ["荔湾", "越秀", "天河","海珠","白云", "黄埔", "番禺", "花都", "增城", "从化", "其它"] %>
  <%= f.input :address %>
  <%= f.input :grade, collection: ["幼儿","一年级","二年级","三年级","四年级","五年级","六年级","初一","初二","初三","高一","高二","高三"] %>
  <%= f.input :subject_list, collection: Subject.all.map(&:name), input_html: {class: 'subjects', multiple: true} %>
  <%= f.input :fee, collection: ["面议","10元/小时", "20元/小时","30-50元/小时","50-100元/小时","100-200元/小时","200-300元/小时"] %>
  <%= f.input :time %>
  <%= f.input :demand, input_html: {rows: 6, class: "span5"} %>
  <%= f.input :status, inline_label: "状态", label: false %>
  <div class="span2 offset6">
  <%= f.button :submit, class: 'btn btn-info'%>
  </div>
<% end %>

app/views/student_infos/_student_info.html.erb
<%= link_to "修改", edit_student_info_path(student_info), class: "pull-right" if can? :update, student_info %>
<table class="table table-bordered">
  <tr>
    <td>联系人</td>    
    <td><%= student_info.username %></td>
  </tr>
  <tr>
    <td>性别</td>
    <td><%= student_info.gender %></td>
  </tr>
  <tr>
    <td>联系电话</td>
    <td><%= student_info.phone%></td>
  </tr>
  <tr>
    <td>区域</td>
    <td><%= student_info.area%></td>
  </tr>
  <tr>
    <td>详细地址</td>
    <td><%= student_info.address%></td>
  </tr>
  <tr>
    <td>年级</td>
    <td><%= student_info.grade%></td>
  </tr>
  <tr>
    <td>科目</td>
    <td><%= student_info.subject_list %></td>
  </tr>
  <tr>
    <td>收费标准</td>
    <td><%= student_info.fee%></td>
  </tr>
  <tr>
    <td>上课时间</td>
    <td><%= student_info.time%></td>
  </tr>
  <tr>
    <td>学员需求</td>
    <td><%= student_info.demand%></td>
  </tr>
  <tr>
    <td>状态</td>
    <td>
      <% if student_info.status == true %>
       有效
      <% else %>
       无效
      <% end %>
    </td>
  </tr>
</table>

app/views/student_infos/edit.html.erb
<%= render 'form' %>

app/views/student_infos/index.html.erb
<%= render 'searches/form' %>
<table class="table table-hover">
  <caption>学员库</caption>  
  <tr>
    <th>订单编号</th>
    <th>性别</th>
    <th>年级</th>
    <th>求教科目</th>
    <th>区域位置</th>
    <th>课时费用</th>
    <th>要求</th>
    <th>状态</th>
    <th>详情</th>
  </tr>
    <% @student_infos.each do |s| %>
  <tbody>
    <tr>
      <td><%= s.id %></td>
      <td><%= s.gender %></td>
      <td><%= s.grade %></td>
      <td><%= s.subject_list %></td>
      <td><%= s.area %> : <%= s.address %></td>
      <td><%= s.fee %></td>
      <td class="span3"><%= truncate(strip_tags(s.demand), length: 20)%></td>
      <td>
        <% if s.status == true %>
          有效
        <% else %>
          无效
        <% end %>
      </td>
      <td><%= link_to "查看", s %></td>
    </tr>
  </tbody>
    <% end %>
</table>

app/views/student_infos/new.html.erb
<h1>请填写详细请家教信息</h1>
<%= render 'form' %>

app/views/student_infos/show.html.erb
<%= render 'student_info', student_info: @student_info %>