config/routes.rb
SunnyTutorial::Application.routes.draw do
  resources :users
  resources :student_infos
  resources :tutor_infos
  resources :searches
  resources :messages
  get 'login' => "sessions#new", as: :log_in
  match 'logout' => "sessions#destroy", as: :log_out
  get 'signup' => "users#create", as: :sign_up
  resources :sessions, only: :create
  root to: 'static_page#home', as: :home
  get 'guangzhou' => 'static_page#display', as: :guangzhou
end

app/models/tutor_info.rb
class TutorInfo < ActiveRecord::Base
  belongs_to :user
  attr_accessible :gender, :username, :date_of_birth, :major, :school, :identity, :area, :address, :phone, :qq,
                  :fee, :time, :experience, :status, :subject_list, :user_id 
  has_many :teachings
  has_many :subjects, through: :teachings
  validates_presence_of :username, :gender, :date_of_birth, :major, :school, :identity, :area, :address, :phone,
                        :fee, :time, :experience, :subject_list
  default_scope order("created_at DESC")

  def subject_list=(names)
    self.subjects = names.split(",").map do |n|
      Subject.find_by_name(n)
    end
  end

  def subject_list
    subjects.map(&:name).join(',')
  end
end

app/controllers/tutor_infos_controller.rb
class TutorInfosController < ApplicationController
  load_and_authorize_resource

  def index
    @tutor_infos = params[:search_id] ? Search.find(params[:search_id]).find_tutor_infos : TutorInfo.all
    @search = Search.new(search_type: "tutor")
  end
  
  def new
    unless current_user.tutor_info.nil?
      redirect_to current_user.tutor_info, notice: "你已申请一份教员资料"
    end
    @tutor_info = TutorInfo.new
  end

  def create
    if current_user.tutor_info.nil?
      @tutor_info = TutorInfo.new(params[:tutor_info].merge!(user_id: current_user.id))
      if @tutor_info.save
        redirect_to @tutor_info, notice: "新建成功"
      else
        render :new
      end
    else
      redirect_to :guangzhou, notice: "你已申请一份教员资料"
    end
  end

  def update
    if @tutor_info.update_attributes(params[:tutor_info])
      redirect_to @tutor_info, notice: "修改成功"
    else
      render :edit
    end
  end
  
  def destroy
    @tutor_info.destroy
    redirect_to :guangzhou, notice: "删除成功"
  end
end

app/views/tutor_infos/_form.html.erb
<%= simple_form_for @tutor_info, html: {class: 'form-horizontal'} do |f| %>
  <legend>基本信息</legend>
    <%= f.input :username  %>
    <%= f.input :gender, collection: ["男","女"] , as: :radio_buttons %>
    <%= f.input :date_of_birth, as: :date, start_year: Date.today.year - 60,
                      end_year: Date.today.year - 12, discard_day: true, order: [:year, :month] %>
    <hr />
  <legend>联系方式</legend>
    <%= f.input :area, collection: ["荔湾", "越秀", "天河","海珠","白云", "黄埔", "番禺", "花都", "增城", "从化", "其它"] %>
    <%= f.input :address %>
    <%= f.input :phone %>
    <%= f.input :qq %><hr />
 <legend>详细资料</legend>
    <%= f.input :school %>
    <%= f.input :major %>
    <%= f.input :identity, collection: ["在校学生", "教师"], as: :radio_buttons, multiple: true %>
    <%= f.input :fee, collection: ["面议","10元/小时", "20元/小时","30-50元/小时","50-100元/小时","100-200元/小时","200-300元/小时"] %>
    <%= f.input :subject_list, collection: Subject.all.map(&:name), input_html: {class: 'subjects', multiple: true}%>
    <%= f.input :time %>
    <%= f.input :experience, input_html: {rows: 6, class: "span5"} %>
    <%= f.input :status%>
    <div class="span2 offset6">
      <%= f.button :submit, class: 'btn btn-primary'%>
    </div>
<% end %>

app/views/tutor_infos/_tutor_info.html.erb
<%= link_to "修改", edit_tutor_info_path(tutor_info), class: "pull-right" if can? :update, tutor_info %>
<table class="table table-bordered">
  <tr>
    <th>########</th>
  </tr>
  <tr>
    <td>教员编号</td>
    <td><%= tutor_info.id %></td>
  </tr>
  <tr>
    <td>真实姓名:</td>
    <td> <%= tutor_info.username %> </td>
  </tr>
  <tr>
    <td>性别</td>
    <td><%= tutor_info.gender %></td>
  </tr>
  <tr>
    <td>出生日期</td>
    <td><%= tutor_info.date_of_birth %></td>
  </tr>
  <tr>
    <td>所在地区</td>
    <td><%= tutor_info.area %></td>    
  </tr>
  <tr>
    <td>详细地址</td>
    <td><%= tutor_info.address %></td>
  </tr>
  <tr>
    <td>联系电话</td>
    <td><%= tutor_info.phone %></td>
  </tr>
  <tr>
    <td>qq号码</td>
    <td><%= tutor_info.qq %></td>
  </tr>
  <tr>
    <td>毕业高校</td>
    <td><%= tutor_info.school %></td>    
  </tr>
  <tr>
    <td>专业</td>
    <td><%= tutor_info.major %></td>
  </tr>
  <tr>
    <td>授教学科</td>
    <td><%= tutor_info.subject_list %></td>
  </tr>
  <tr>
    <td>现在身份</td>
    <td><%= tutor_info.identity %></td>
  </tr>
  <tr>
    <td>上课时间</td>
    <td><%= tutor_info.time %></td>
  </tr>
  <tr>
    <td>经验</td>
    <td><%= simple_format tutor_info.experience %></td>
  </tr>
  <tr>
    <td>状态</td>
    <td>
      <% if tutor_info.status == true %>
        有效
      <% else %>
        无效
      <% end %>
    </td>
  </tr>
</table>

app/views/tutor_infos/edit.html.erb
<h1 class="text-center">修改资料</h1>
<br />
<%= render 'form' %>

app/views/tutor_infos/index.html.erb
<div>
  <%= render 'searches/form' %>
</div>
<table class="table table-hover">
  <caption>教员库</caption>
    <tr>
      <th>教员编号</th>
      <th>目前身份</th>
      <th>学校</th>
      <th>专业</th>
      <th>区域</th>
      <th>经验</th>
      <th>状态</th>
      <th>详情</th>
      <th></th>
    </tr>
  <% @tutor_infos.each do |t| %>
    <tbody>
    <tr>
      <td><%= t.id %></td>
      <td><%= t.identity %></td>
      <td><%= t.school %></td>
      <td><%= t.major %></td>
      <td><%= t.area %></td>
      <td class="span3"><%= truncate(strip_tags(t.experience), length:30) %></td>
      <td>
        <% if t.status == true %>
          有效
        <% else %>
          无效
        <% end %>
      </td>
      <td><%= link_to "查看", t %></td>
    </tr>
    </tbody>
  <% end %>
</table>

app/views/tutor_infos/show.html.erb
<%= render 'tutor_info', tutor_info: @tutor_info%>