config/routes.rb
SunnyTutorial::Application.routes.draw do
  resources :users
  resources :student_infos
  resources :tutor_infos
  resources :searches
  resources :messages
  get 'login' => "sessions#new", as: :log_in
  match 'logout' => "sessions#destroy", as: :log_out
  get 'signup' => "users#create", as: :sign_up
  resources :sessions, only: :create
  root to: 'static_page#home', as: :home
  get 'guangzhou' => 'static_page#display', as: :guangzhou
end

app/views/layouts/_alert.html.erb
<% flash.each do |key, value|   %>
  <div class="alert alert-<%= key %> span9">
  <button type="submit" class="close" data-dismiss="alert">&times;</button>
  <%= value %>
</div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="navbar navbar-fixeed-top">
<div class="navbar-inner">
  <div class="container">
    <ul class="nav">
       <li class='divider-vertical'><%= link_to "首页", home_path%></li>
       <li class='divider-vertical'><%= link_to "广州站", guangzhou_path%></li>
       <li class='divider-vertical'><%= link_to "教员库", tutor_infos_path %></li>
       <li class='divider-vertical'><%= link_to "学员库", student_infos_path %></li>
       <li class='divider-vertical'><%= link_to "做家教",  new_tutor_info_path%></li>
       <li class='divider-vertical'><%= link_to "请家教", new_student_info_path%></li>
       <li class='divider-vertical'><%= link_to "讨论区", messages_path %></li>
       <li class='divider-vertical'><a href="javascript:void(0)" onClick="addCookie()" >收藏本站</a></li>
    </ul>
    <ul class="nav pull-right">
    <% if current_user.nil? %>
      <li><%= link_to "登录", log_in_path %></li>
    <% else %>
      <div class="btn-group pull-right">
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <%= current_user.name %>
        <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "我的资料", current_user %></li>
          <li class="divider"></li>
          <li><%= link_to '退出', log_out_path, method: :delete, confirm: "Are you sure" %></li>
        </ul>
        </div>
      </ul>
     <% end %>
  </div>  
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunnyTutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
  <div class="row">
    <div class="span9 offset1">
      <div class="alert alert-info text-center span9">
      欢迎来到 <strong>Sunny</strong> 家教网 
      </div>
      <br />
      <%= render 'layouts/alert' %>
      <%= yield %>
    </div>    
  </div>
</div>
</body>
</html>

app/views/layouts/static_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunnyTutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>